                                                                                                statusDot.classList.remove('active');
                                                                                                                                                                                                                                                                    charMapWrap.style.display    = 'none';
                                                                                                                                                                                                                                                                      showCharMapCb.checked        = false;
                                                                                                                                                                                                                                                                        charMapContainer.style.display = 'none';
                                                                                                                                                                                                                                                                          charMapContainer.innerHTML   = '';

                                                                                                                                                                                                                                                                            copyBtn.disabled = true;
                                                                                                                                                                                                                                                                              swapBtn.disabled = true;
                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                              /**
                                                                                                                                                                                                                                                                               * Clear all inputs and outputs.
                                                                                                                                                                                                                                                                                */
                                                                                                                                                                                                                                                                                function clearAll() {
                                                                                                                                                                                                                                                                                  inputText.value      = '';
                                                                                                                                                                                                                                                                                    keyInput.value       = '';
                                                                                                                                                                                                                                                                                      keyStrength.textContent = '';
                                                                                                                                                                                                                                                                                        keyStrength.className   = 'key-strength';
                                                                                                                                                                                                                                                                                          clearOutput();
                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                          // ── Character Mapping ──────────────────────────────────────

                                                                                                                                                                                                                                                                                          /**
                                                                                                                                                                                                                                                                                           * Build the visual character-by-character mapping.
                                                                                                                                                                                                                                                                                            * Capped at 60 characters for performance.
                                                                                                                                                                                                                                                                                             */
                                                                                                                                                                                                                                                                                             function buildCharMap(original, result, key) {
                                                                                                                                                                                                                                                                                               const cleanKey = key.toUpperCase().replace(/[^A-Z]/g, '');
                                                                                                                                                                                                                                                                                                 charMapContainer.innerHTML = '';

                                                                                                                                                                                                                                                                                                   const MAX_CHARS = 60;
                                                                                                                                                                                                                                                                                                     const limit = Math.min(original.length, MAX_CHARS);
                                                                                                                                                                                                                                                                                                       let keyIndex = 0;

                                                                                                                                                                                                                                                                                                         for (let i = 0; i < limit; i++) {
                                                                                                                                                                                                                                                                                                             const origChar   = original[i];
                                                                                                                                                                                                                                                                                                                 const resultChar = result[i];
                                                                                                                                                                                                                                                                                                                     const isLetter   = /[a-zA-Z]/.test(origChar);

                                                                                                                                                                                                                                                                                                                         const pair = document.createElement('div');
                                                                                                                                                                                                                                                                                                                             pair.className = 'char-pair';

                                                                                                                                                                                                                                                                                                                                 const topSpan = document.createElement('span');
                                                                                                                                                                                                                                                                                                                                     topSpan.className   = 'char-orig';
                                                                                                                                                                                                                                                                                                                                         topSpan.textContent = origChar === ' ' ? '·' : origChar;

                                                                                                                                                                                                                                                                                                                                             const botSpan = document.createElement('span');
                                                                                                                                                                                                                                                                                                                                                 botSpan.className   = 'char-enc' + (origChar === ' ' ? ' space' : '');
                                                                                                                                                                                                                                                                                                                                                     botSpan.textContent = resultChar === ' ' ? '·' : resultChar;

                                                                                                                                                                                                                                                                                                                                                         if (isLetter) {
                                                                                                                                                                                                                                                                                                                                                               const keyLetter = cleanKey[keyIndex % cleanKey.length];
                                                                                                                                                                                                                                                                                                                                                                     const shift     = keyLetter.charCodeAt(0) - 65;
                                                                                                                                                                                                                                                                                                                                                                           botSpan.title   = `Key: ${keyLetter} (shift ${shift})`;
                                                                                                                                                                                                                                                                                                                                                                                 keyIndex++;
                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                         pair.appendChild(topSpan);
                                                                                                                                                                                                                                                                                                                                                                                             pair.appendChild(botSpan);
                                                                                                                                                                                                                                                                                                                                                                                                 charMapContainer.appendChild(pair);
                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                     if (original.length > MAX_CHARS) {
                                                                                                                                                                                                                                                                                                                                                                                                         const more = document.createElement('span');
                                                                                                                                                                                                                                                                                                                                                                                                             more.className   = 'char-map-more';
                                                                                                                                                                                                                                                                                                                                                                                                                 more.textContent = `+${original.length - MAX_CHARS} more`;
                                                                                                                                                                                                                                                                                                                                                                                                                     charMapContainer.appendChild(more);
                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                       /**
                                                                                                                                                                                                                                                                                                                                                                                                                        * Show or hide the character map based on checkbox state.
                                                                                                                                                                                                                                                                                                                                                                                                                         */
                                                                                                                                                                                                                                                                                                                                                                                                                         function toggleCharMap() {
                                                                                                                                                                                                                                                                                                                                                                                                                           charMapContainer.style.display = showCharMapCb.checked ? 'flex' : 'none';
                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                           // ── Clipboard ──────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                           /**
                                                                                                                                                                                                                                                                                                                                                                                                                            * Copy the output text to the clipboard.
                                                                                                                                                                                                                                                                                                                                                                                                                             */
                                                                                                                                                                                                                                                                                                                                                                                                                             function copyOutput() {
                                                                                                                                                                                                                                                                                                                                                                                                                               if (!outputResult) { showToast('Nothing to copy yet.', false); return; }

                                                                                                                                                                                                                                                                                                                                                                                                                                 navigator.clipboard.writeText(outputResult)
                                                                                                                                                                                                                                                                                                                                                                                                                                     .then(() => showToast('Copied to clipboard!', true))
                                                                                                                                                                                                                                                                                                                                                                                                                                         .catch(() => showToast('Copy failed — please select and copy manually.', false));

                                                                                                                                                                                                                                                                                                                                                                                                                                           // Flash the output body
                                                                                                                                                                                                                                                                                                                                                                                                                                             outputBody.classList.remove('flash');
                                                                                                                                                                                                                                                                                                                                                                                                                                               void outputBody.offsetWidth; // Force reflow to restart animation
                                                                                                                                                                                                                                                                                                                                                                                                                                                 outputBody.classList.add('flash');
                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                 /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                  * Move the current output into the input field and flip the mode.
                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
                                                                                                                                                                                                                                                                                                                                                                                                                                                   function swapToInput() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (!outputResult) { showToast('Nothing to swap yet.', false); return; }

                                                                                                                                                                                                                                                                                                                                                                                                                                                       inputText.value = outputResult;
                                                                                                                                                                                                                                                                                                                                                                                                                                                         setMode(currentMode === 'encrypt' ? 'decrypt' : 'encrypt');
                                                                                                                                                                                                                                                                                                                                                                                                                                                           showToast('Output moved to input!', true);

                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Scroll to the top of the input card
                                                                                                                                                                                                                                                                                                                                                                                                                                                               inputText.scrollIntoView({ behavior: 'smooth', block: 'center' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                                                                               // ── Key Strength Indicator ─────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                               keyInput.addEventListener('input', function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // Strip non-alpha characters immediately
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   this.value = this.value.replace(/[^a-zA-Z]/g, '');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const len = this.value.length;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (!len) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           keyStrength.textContent = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               keyStrength.className   = 'key-strength';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (len < 4) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           keyStrength.textContent = 'WEAK';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               keyStrength.className   = 'key-strength strength-weak';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } else if (len < 8) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     keyStrength.textContent = 'FAIR';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         keyStrength.className   = 'key-strength strength-fair';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               keyStrength.textContent = 'STRONG';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   keyStrength.className   = 'key-strength strength-strong';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // Allow pressing Enter in the key field to trigger processing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     keyInput.addEventListener('keydown', e => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (e.key === 'Enter') process();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // ── Toast Notification ─────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * Show a transient toast message.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * @param {string}  message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * @param {boolean} success - true = green, false = red
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           function showToast(message, success) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             toast.className = `toast ${success ? 'success' : 'error'}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               toastMsg.textContent = message;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 toast.classList.add('show');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   clearTimeout(toastTimer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     toastTimer = setTimeout(() => toast.classList.remove('show'), 2600);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // ── Alphabet Reference Table ───────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     (function buildAlphaTable() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const table = document.getElementById('alphaTable');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         for (let i = 0; i < 26; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const cell = document.createElement('div');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 cell.className = 'alpha-cell';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const letter = document.createElement('span');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         letter.className   = 'letter';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             letter.textContent = String.fromCharCode(65 + i);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const num = document.createElement('span');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     num.className   = 'num';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         num.textContent = i;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             cell.appendChild(letter);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 cell.appendChild(num);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     table.appendChild(cell);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       })();
