/* ============================================================
   SecretWeave — script.js
      Vigenère Cipher App
         ============================================================ */

         'use strict';

         // ── State ──────────────────────────────────────────────────
         let currentMode   = 'encrypt';
         let outputResult  = '';
         let toastTimer    = null;

         // ── DOM References ─────────────────────────────────────────
         const inputText       = document.getElementById('inputText');
         const keyInput        = document.getElementById('keyInput');
         const keyStrength     = document.getElementById('keyStrength');
         const actionBtn       = document.getElementById('actionBtn');
         const inputLabel      = document.getElementById('inputLabel');
         const outputLabel     = document.getElementById('outputLabel');
         const statusDot       = document.getElementById('statusDot');
         const outputBody      = document.getElementById('outputBody');
         const outputPlaceholder = document.getElementById('outputPlaceholder');
         const outputTextEl    = document.getElementById('outputText');
         const charMapWrap     = document.getElementById('charMapWrap');
         const charMapContainer = document.getElementById('charMapContainer');
         const showCharMapCb   = document.getElementById('showCharMap');
         const copyBtn         = document.getElementById('copyBtn');
         const swapBtn         = document.getElementById('swapBtn');
         const toast           = document.getElementById('toast');
         const toastMsg        = document.getElementById('toastMsg');

         // ── Vigenère Core ──────────────────────────────────────────

         /**
          * Encrypt or decrypt text using the Vigenère cipher.
           * Non-alphabetic characters are passed through unchanged.
            *
             * @param {string}  text    - Input text
              * @param {string}  key     - Cipher key (letters only)
               * @param {boolean} encrypt - true = encrypt, false = decrypt
                * @returns {string}
                 */
                 function vigenere(text, key, encrypt) {
                   const cleanKey = key.toUpperCase().replace(/[^A-Z]/g, '');
                     if (!cleanKey) return text;

                       let keyIndex = 0;

                         return text.split('').map(char => {
                             if (/[a-zA-Z]/.test(char)) {
                                   const base  = char >= 'a' ? 97 : 65;
                                         const shift = cleanKey.charCodeAt(keyIndex % cleanKey.length) - 65;
                                               keyIndex++;

                                                     const code = encrypt
                                                             ? ((char.charCodeAt(0) - base + shift) % 26) + base
                                                                     : ((char.charCodeAt(0) - base - shift + 26) % 26) + base;

                                                                           return String.fromCharCode(code);
                                                                               }
                                                                                   return char;
                                                                                     }).join('');
                                                                                     }

                                                                                     // ── Mode ───────────────────────────────────────────────────

                                                                                     /**
                                                                                      * Switch between encrypt / decrypt modes.
                                                                                       * @param {'encrypt'|'decrypt'} mode
                                                                                        */
                                                                                        function setMode(mode) {
                                                                                          currentMode = mode;

                                                                                            const encBtn = document.getElementById('encryptBtn');
                                                                                              const decBtn = document.getElementById('decryptBtn');

                                                                                                encBtn.classList.toggle('active', mode === 'encrypt');
                                                                                                  decBtn.classList.toggle('active', mode === 'decrypt');
                                                                                                    encBtn.setAttribute('aria-pressed', mode === 'encrypt');
                                                                                                      decBtn.setAttribute('aria-pressed', mode === 'decrypt');

                                                                                                        actionBtn.className = `btn-primary ${mode}-mode`;

                                                                                                          if (mode === 'encrypt') {
                                                                                                              actionBtn.innerHTML = `
                                                                                                                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" aria-hidden="true">
                                                                                                                            <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                                                                                                                  </svg>
                                                                                                                                        Encrypt Message`;
                                                                                                                                            inputLabel.textContent  = 'Plain Text';
                                                                                                                                                outputLabel.textContent = 'Encrypted Output';
                                                                                                                                                  } else {
                                                                                                                                                      actionBtn.innerHTML = `
                                                                                                                                                            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" aria-hidden="true">
                                                                                                                                                                    <path d="M8 11V7a4 4 0 118 0m-4 8v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2z"/>
                                                                                                                                                                          </svg>
                                                                                                                                                                                Decrypt Message`;
                                                                                                                                                                                    inputLabel.textContent  = 'Cipher Text';
                                                                                                                                                                                        outputLabel.textContent = 'Decrypted Output';
                                                                                                                                                                                          }

                                                                                                                                                                                            clearOutput();
                                                                                                                                                                                            }

                                                                                                                                                                                            // ── Process ────────────────────────────────────────────────

                                                                                                                                                                                            /**
                                                                                                                                                                                             * Read inputs, run the cipher, display output.
                                                                                                                                                                                              */
                                                                                                                                                                                              function process() {
                                                                                                                                                                                                const text = inputText.value;
                                                                                                                                                                                                  const key  = keyInput.value;

                                                                                                                                                                                                    if (!text.trim()) { showToast('Please enter some text.', false); return; }
                                                                                                                                                                                                      if (!key.trim())  { showToast('Please enter a key.', false); return; }

                                                                                                                                                                                                        // Show loading state
                                                                                                                                                                                                          const originalHTML = actionBtn.innerHTML;
                                                                                                                                                                                                            actionBtn.innerHTML = '<span class="spinner"></span> Processing…';
                                                                                                                                                                                                              actionBtn.disabled  = true;

                                                                                                                                                                                                                // Small timeout to allow the browser to repaint before potentially heavy work
                                                                                                                                                                                                                  setTimeout(() => {
                                                                                                                                                                                                                      outputResult = vigenere(text, key, currentMode === 'encrypt');
                                                                                                                                                                                                                          renderOutput(outputResult, text, key);
                                                                                                                                                                                                                              actionBtn.innerHTML = originalHTML;
                                                                                                                                                                                                                                  actionBtn.disabled  = false;
                                                                                                                                                                                                                                    }, 160);
                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                     * Display the cipher result and update UI state.
                                                                                                                                                                                                                                      */
                                                                                                                                                                                                                                      function renderOutput(result, original, key) {
                                                                                                                                                                                                                                        outputPlaceholder.style.display = 'none';
                                                                                                                                                                                                                                          outputTextEl.style.display      = 'block';
                                                                                                                                                                                                                                            outputTextEl.textContent        = result;

                                                                                                                                                                                                                                              statusDot.classList.add('active');
                                                                                                                                                                                                                                                charMapWrap.style.display = 'block';
                                                                                                                                                                                                                                                  copyBtn.disabled          = false;
                                                                                                                                                                                                                                                    swapBtn.disabled          = false;

                                                                                                                                                                                                                                                      buildCharMap(original, result, key);
                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                      /**
                                                                                                                                                                                                                                                       * Reset the output area to its empty state.
                                                                                                                                                                                                                                                        */
                                                                                                                                                                                                                                                        function clearOutput() {
                                                                                                                                                                                                                                                          outputResult = '';
                                                                                                                                                                                                                                                            outputPlaceholder.style.display = 'flex';
                                                                                                                                                                                                                                                              outputTextEl.style.display      = 'none';
                                                                                                                                                                                                                                                                outputTextEl.textContent        = '';

                                                                                                                                                                                                                                                                  statusDot.classList.remove('active');
                                                                                                                                                                                                                                                                    charMapWrap.style.display    = 'none';
                                                                                                                                                                                                                                                                      showCharMapCb.checked        = false;
                                                                                                                                                                                                                                                                        charMapContainer.style.display = 'none';
                                                                                                                                                                                                                                                                          charMapContainer.innerHTML   = '';

                                                                                                                                                                                                                                                                            copyBtn.disabled = true;
                                                                                                                                                                                                                                                                              swapBtn.disabled = true;
                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                              /**
                                                                                                                                                                                                                                                                               * Clear all inputs and outputs.
                                                                                                                                                                                                                                                                                */
                                                                                                                                                                                                                                                                                function clearAll() {
                                                                                                                                                                                                                                                                                  inputText.value      = '';
                                                                                                                                                                                                                                                                                    keyInput.value       = '';
                                                                                                                                                                                                                                                                                      keyStrength.textContent = '';
                                                                                                                                                                                                                                                                                        keyStrength.className   = 'key-strength';
                                                                                                                                                                                                                                                                                          clearOutput();
                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                          // ── Character Mapping ──────────────────────────────────────

                                                                                                                                                                                                                                                                                          /**
                                                                                                                                                                                                                                                                                           * Build the visual character-by-character mapping.
                                                                                                                                                                                                                                                                                            * Capped at 60 characters for performance.
                                                                                                                                                                                                                                                                                             */
                                                                                                                                                                                                                                                                                             function buildCharMap(original, result, key) {
                                                                                                                                                                                                                                                                                               const cleanKey = key.toUpperCase().replace(/[^A-Z]/g, '');
                                                                                                                                                                                                                                                                                                 charMapContainer.innerHTML = '';

                                                                                                                                                                                                                                                                                                   const MAX_CHARS = 60;
                                                                                                                                                                                                                                                                                                     const limit = Math.min(original.length, MAX_CHARS);
                                                                                                                                                                                                                                                                                                       let keyIndex = 0;

                                                                                                                                                                                                                                                                                                         for (let i = 0; i < limit; i++) {
                                                                                                                                                                                                                                                                                                             const origChar   = original[i];
                                                                                                                                                                                                                                                                                                                 const resultChar = result[i];
                                                                                                                                                                                                                                                                                                                     const isLetter   = /[a-zA-Z]/.test(origChar);

                                                                                                                                                                                                                                                                                                                         const pair = document.createElement('div');
                                                                                                                                                                                                                                                                                                                             pair.className = 'char-pair';

                                                                                                                                                                                                                                                                                                                                 const topSpan = document.createElement('span');
                                                                                                                                                                                                                                                                                                                                     topSpan.className   = 'char-orig';
                                                                                                                                                                                                                                                                                                                                         topSpan.textContent = origChar === ' ' ? '·' : origChar;

                                                                                                                                                                                                                                                                                                                                             const botSpan = document.createElement('span');
                                                                                                                                                                                                                                                                                                                                                 botSpan.className   = 'char-enc' + (origChar === ' ' ? ' space' : '');
                                                                                                                                                                                                                                                                                                                                                     botSpan.textContent = resultChar === ' ' ? '·' : resultChar;

                                                                                                                                                                                                                                                                                                                                                         if (isLetter) {
                                                                                                                                                                                                                                                                                                                                                               const keyLetter = cleanKey[keyIndex % cleanKey.length];
                                                                                                                                                                                                                                                                                                                                                                     const shift     = keyLetter.charCodeAt(0) - 65;
                                                                                                                                                                                                                                                                                                                                                                           botSpan.title   = `Key: ${keyLetter} (shift ${shift})`;
                                                                                                                                                                                                                                                                                                                                                                                 keyIndex++;
                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                         pair.appendChild(topSpan);
                                                                                                                                                                                                                                                                                                                                                                                             pair.appendChild(botSpan);
                                                                                                                                                                                                                                                                                                                                                                                                 charMapContainer.appendChild(pair);
                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                     if (original.length > MAX_CHARS) {
                                                                                                                                                                                                                                                                                                                                                                                                         const more = document.createElement('span');
                                                                                                                                                                                                                                                                                                                                                                                                             more.className   = 'char-map-more';
                                                                                                                                                                                                                                                                                                                                                                                                                 more.textContent = `+${original.length - MAX_CHARS} more`;
                                                                                                                                                                                                                                                                                                                                                                                                                     charMapContainer.appendChild(more);
                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                       /**
                                                                                                                                                                                                                                                                                                                                                                                                                        * Show or hide the character map based on checkbox state.
                                                                                                                                                                                                                                                                                                                                                                                                                         */
                                                                                                                                                                                                                                                                                                                                                                                                                         function toggleCharMap() {
                                                                                                                                                                                                                                                                                                                                                                                                                           charMapContainer.style.display = showCharMapCb.checked ? 'flex' : 'none';
                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                           // ── Clipboard ──────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                           /**
                                                                                                                                                                                                                                                                                                                                                                                                                            * Copy the output text to the clipboard.
                                                                                                                                                                                                                                                                                                                                                                                                                             */
                                                                                                                                                                                                                                                                                                                                                                                                                             function copyOutput() {
                                                                                                                                                                                                                                                                                                                                                                                                                               if (!outputResult) { showToast('Nothing to copy yet.', false); return; }

                                                                                                                                                                                                                                                                                                                                                                                                                                 navigator.clipboard.writeText(outputResult)
                                                                                                                                                                                                                                                                                                                                                                                                                                     .then(() => showToast('Copied to clipboard!', true))
                                                                                                                                                                                                                                                                                                                                                                                                                                         .catch(() => showToast('Copy failed — please select and copy manually.', false));

                                                                                                                                                                                                                                                                                                                                                                                                                                           // Flash the output body
                                                                                                                                                                                                                                                                                                                                                                                                                                             outputBody.classList.remove('flash');
                                                                                                                                                                                                                                                                                                                                                                                                                                               void outputBody.offsetWidth; // Force reflow to restart animation
                                                                                                                                                                                                                                                                                                                                                                                                                                                 outputBody.classList.add('flash');
                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                 /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                  * Move the current output into the input field and flip the mode.
                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
                                                                                                                                                                                                                                                                                                                                                                                                                                                   function swapToInput() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (!outputResult) { showToast('Nothing to swap yet.', false); return; }

                                                                                                                                                                                                                                                                                                                                                                                                                                                       inputText.value = outputResult;
                                                                                                                                                                                                                                                                                                                                                                                                                                                         setMode(currentMode === 'encrypt' ? 'decrypt' : 'encrypt');
                                                                                                                                                                                                                                                                                                                                                                                                                                                           showToast('Output moved to input!', true);

                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Scroll to the top of the input card
                                                                                                                                                                                                                                                                                                                                                                                                                                                               inputText.scrollIntoView({ behavior: 'smooth', block: 'center' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                                                                               // ── Key Strength Indicator ─────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                               keyInput.addEventListener('input', function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // Strip non-alpha characters immediately
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   this.value = this.value.replace(/[^a-zA-Z]/g, '');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const len = this.value.length;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (!len) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           keyStrength.textContent = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               keyStrength.className   = 'key-strength';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (len < 4) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           keyStrength.textContent = 'WEAK';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               keyStrength.className   = 'key-strength strength-weak';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } else if (len < 8) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     keyStrength.textContent = 'FAIR';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         keyStrength.className   = 'key-strength strength-fair';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               keyStrength.textContent = 'STRONG';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   keyStrength.className   = 'key-strength strength-strong';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // Allow pressing Enter in the key field to trigger processing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     keyInput.addEventListener('keydown', e => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (e.key === 'Enter') process();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // ── Toast Notification ─────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * Show a transient toast message.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * @param {string}  message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * @param {boolean} success - true = green, false = red
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           function showToast(message, success) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             toast.className = `toast ${success ? 'success' : 'error'}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               toastMsg.textContent = message;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 toast.classList.add('show');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   clearTimeout(toastTimer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     toastTimer = setTimeout(() => toast.classList.remove('show'), 2600);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // ── Alphabet Reference Table ───────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     (function buildAlphaTable() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const table = document.getElementById('alphaTable');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         for (let i = 0; i < 26; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const cell = document.createElement('div');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 cell.className = 'alpha-cell';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const letter = document.createElement('span');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         letter.className   = 'letter';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             letter.textContent = String.fromCharCode(65 + i);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const num = document.createElement('span');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     num.className   = 'num';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         num.textContent = i;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             cell.appendChild(letter);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 cell.appendChild(num);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     table.appendChild(cell);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       })();